// Generates supabase/seed.sql from the static data in src/data/content.ts.
// Run: npx tsx scripts/gen-seed.ts
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import {
  CITIES,
  ARTICLES,
  FIGURES,
  HISTORY_EVENTS,
} from "../src/data/content.ts";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../supabase/seed.sql");

const s = (v: unknown): string =>
  v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;
const n = (v: unknown): string =>
  v === null || v === undefined ? "NULL" : String(Number(v));
const arr = (v: unknown): string => {
  if (!Array.isArray(v) || v.length === 0) return "ARRAY[]::text[]";
  return `ARRAY[${v.map((x) => s(x)).join(",")}]::text[]`;
};
const json = (v: unknown): string =>
  `'${JSON.stringify(v ?? []).replace(/'/g, "''")}'::jsonb`;

function insert(table: string, cols: string[], rows: string[][]): string {
  const values = rows.map((r) => `  (${r.join(", ")})`).join(",\n");
  return `insert into public.${table} (${cols.join(", ")}) values\n${values}\non conflict (id) do nothing;\n`;
}

const blocks: string[] = ["-- Auto-generated by scripts/gen-seed.ts — do not edit by hand.\n"];

blocks.push(
  insert(
    "cities",
    [
      "id","name","name_en","region","status","founded_year","founded_year_en",
      "population_before_1948","short_desc","short_desc_en","description","description_en",
      "geography","geography_en","history","history_en","natives","natives_en",
      "highlights","highlights_en","naming","naming_en","zionist_name","zionist_name_en",
      "brief","brief_en","image","gallery","date","date_en","sort_order",
    ],
    CITIES.map((c, i) => [
      s(c.id), s(c.name), s(c.nameEn), s(c.region), s(c.status), s(c.foundedYear),
      s(c.foundedYearEn), s(c.populationBefore1948), s(c.shortDesc), s(c.shortDescEn),
      s(c.description), s(c.descriptionEn), s(c.geography), s(c.geographyEn),
      s(c.history), s(c.historyEn), s(c.natives), s(c.nativesEn), arr(c.highlights),
      arr(c.highlightsEn), s(c.naming), s(c.namingEn), s(c.zionistName), s(c.zionistNameEn),
      s(c.brief), s(c.briefEn), s(c.image), arr(c.gallery), s(c.date), s(c.dateEn), String(i),
    ]),
  ),
);

blocks.push(
  insert(
    "articles",
    [
      "id","title","title_en","excerpt","excerpt_en","date","date_en","image",
      "category","author","author_en","reading_time","body","body_en","sort_order",
    ],
    ARTICLES.map((a, i) => [
      s(a.id), s(a.title), s(a.titleEn), s(a.excerpt), s(a.excerptEn), s(a.date),
      s(a.dateEn), s(a.image), s(a.category), s(a.author), s(a.authorEn),
      n(a.readingTime), json(a.body), json(a.bodyEn), String(i),
    ]),
  ),
);

blocks.push(
  insert(
    "figures",
    ["id","name","name_en","birth_year","death_year","birth_city","field","bio","bio_en","portrait","sort_order"],
    FIGURES.map((f, i) => [
      s(f.id), s(f.name), s(f.nameEn), n(f.birthYear), n(f.deathYear), s(f.birthCity),
      s(f.field), s(f.bio), s(f.bioEn), s(f.portrait), String(i),
    ]),
  ),
);

blocks.push(
  insert(
    "history_events",
    [
      "id","title","title_en","event_date","event_date_en","iso_date","event_type",
      "description","description_en","image","related_city","sources","sources_en","sort_order",
    ],
    HISTORY_EVENTS.map((h, i) => [
      s(h.id), s(h.title), s(h.titleEn), s(h.eventDate), s(h.eventDateEn), s(h.isoDate),
      s(h.eventType), s(h.description), s(h.descriptionEn), s(h.image), s(h.relatedCity),
      arr(h.sources), arr(h.sourcesEn), String(i),
    ]),
  ),
);

writeFileSync(out, blocks.join("\n"));
console.log(`Wrote ${out}`);
