/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as EnRouteImport } from './routes/en'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as FiguresIndexRouteImport } from './routes/figures.index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as CitiesIndexRouteImport } from './routes/cities.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as FiguresIdRouteImport } from './routes/figures.$id'
import { Route as EnSearchRouteImport } from './routes/en/search'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as CitiesIdRouteImport } from './routes/cities.$id'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminSuggestedRouteImport } from './routes/admin.suggested'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as EnHistoryIndexRouteImport } from './routes/en/history.index'
import { Route as EnFiguresIndexRouteImport } from './routes/en/figures.index'
import { Route as EnCitiesIndexRouteImport } from './routes/en/cities.index'
import { Route as EnArticlesIndexRouteImport } from './routes/en/articles.index'
import { Route as AdminHistoryIndexRouteImport } from './routes/admin.history.index'
import { Route as AdminFiguresIndexRouteImport } from './routes/admin.figures.index'
import { Route as AdminCitiesIndexRouteImport } from './routes/admin.cities.index'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as EnHistoryIdRouteImport } from './routes/en/history.$id'
import { Route as EnFiguresIdRouteImport } from './routes/en/figures.$id'
import { Route as EnCitiesIdRouteImport } from './routes/en/cities.$id'
import { Route as EnArticlesIdRouteImport } from './routes/en/articles.$id'
import { Route as AdminHistoryIdRouteImport } from './routes/admin.history.$id'
import { Route as AdminFiguresIdRouteImport } from './routes/admin.figures.$id'
import { Route as AdminCitiesIdRouteImport } from './routes/admin.cities.$id'
import { Route as AdminArticlesImportRouteImport } from './routes/admin.articles.import'
import { Route as AdminArticlesIdRouteImport } from './routes/admin.articles.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresIndexRoute = FiguresIndexRouteImport.update({
  id: '/figures/',
  path: '/figures/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresIdRoute = FiguresIdRouteImport.update({
  id: '/figures/$id',
  path: '/figures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSearchRoute = EnSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const CitiesIdRoute = CitiesIdRouteImport.update({
  id: '/cities/$id',
  path: '/cities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuggestedRoute = AdminSuggestedRouteImport.update({
  id: '/suggested',
  path: '/suggested',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const EnHistoryIndexRoute = EnHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => EnRoute,
} as any)
const EnFiguresIndexRoute = EnFiguresIndexRouteImport.update({
  id: '/figures/',
  path: '/figures/',
  getParentRoute: () => EnRoute,
} as any)
const EnCitiesIndexRoute = EnCitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => EnRoute,
} as any)
const EnArticlesIndexRoute = EnArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => EnRoute,
} as any)
const AdminHistoryIndexRoute = AdminHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFiguresIndexRoute = AdminFiguresIndexRouteImport.update({
  id: '/figures/',
  path: '/figures/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesIndexRoute = AdminCitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AdminRoute,
} as any)
const EnHistoryIdRoute = EnHistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => EnRoute,
} as any)
const EnFiguresIdRoute = EnFiguresIdRouteImport.update({
  id: '/figures/$id',
  path: '/figures/$id',
  getParentRoute: () => EnRoute,
} as any)
const EnCitiesIdRoute = EnCitiesIdRouteImport.update({
  id: '/cities/$id',
  path: '/cities/$id',
  getParentRoute: () => EnRoute,
} as any)
const EnArticlesIdRoute = EnArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => EnRoute,
} as any)
const AdminHistoryIdRoute = AdminHistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFiguresIdRoute = AdminFiguresIdRouteImport.update({
  id: '/figures/$id',
  path: '/figures/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesIdRoute = AdminCitiesIdRouteImport.update({
  id: '/cities/$id',
  path: '/cities/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesImportRoute = AdminArticlesImportRouteImport.update({
  id: '/articles/import',
  path: '/articles/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suggested': typeof AdminSuggestedRoute
  '/admin/login': typeof AdminLoginRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/cities/$id': typeof CitiesIdRoute
  '/en/about': typeof EnAboutRoute
  '/en/search': typeof EnSearchRoute
  '/figures/$id': typeof FiguresIdRoute
  '/history/$id': typeof HistoryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/en/': typeof EnIndexRoute
  '/figures/': typeof FiguresIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/import': typeof AdminArticlesImportRoute
  '/admin/cities/$id': typeof AdminCitiesIdRoute
  '/admin/figures/$id': typeof AdminFiguresIdRoute
  '/admin/history/$id': typeof AdminHistoryIdRoute
  '/en/articles/$id': typeof EnArticlesIdRoute
  '/en/cities/$id': typeof EnCitiesIdRoute
  '/en/figures/$id': typeof EnFiguresIdRoute
  '/en/history/$id': typeof EnHistoryIdRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/cities/': typeof AdminCitiesIndexRoute
  '/admin/figures/': typeof AdminFiguresIndexRoute
  '/admin/history/': typeof AdminHistoryIndexRoute
  '/en/articles/': typeof EnArticlesIndexRoute
  '/en/cities/': typeof EnCitiesIndexRoute
  '/en/figures/': typeof EnFiguresIndexRoute
  '/en/history/': typeof EnHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suggested': typeof AdminSuggestedRoute
  '/admin/login': typeof AdminLoginRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/cities/$id': typeof CitiesIdRoute
  '/en/about': typeof EnAboutRoute
  '/en/search': typeof EnSearchRoute
  '/figures/$id': typeof FiguresIdRoute
  '/history/$id': typeof HistoryIdRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/cities': typeof CitiesIndexRoute
  '/en': typeof EnIndexRoute
  '/figures': typeof FiguresIndexRoute
  '/history': typeof HistoryIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/import': typeof AdminArticlesImportRoute
  '/admin/cities/$id': typeof AdminCitiesIdRoute
  '/admin/figures/$id': typeof AdminFiguresIdRoute
  '/admin/history/$id': typeof AdminHistoryIdRoute
  '/en/articles/$id': typeof EnArticlesIdRoute
  '/en/cities/$id': typeof EnCitiesIdRoute
  '/en/figures/$id': typeof EnFiguresIdRoute
  '/en/history/$id': typeof EnHistoryIdRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/cities': typeof AdminCitiesIndexRoute
  '/admin/figures': typeof AdminFiguresIndexRoute
  '/admin/history': typeof AdminHistoryIndexRoute
  '/en/articles': typeof EnArticlesIndexRoute
  '/en/cities': typeof EnCitiesIndexRoute
  '/en/figures': typeof EnFiguresIndexRoute
  '/en/history': typeof EnHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suggested': typeof AdminSuggestedRoute
  '/admin_/login': typeof AdminLoginRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/cities/$id': typeof CitiesIdRoute
  '/en/about': typeof EnAboutRoute
  '/en/search': typeof EnSearchRoute
  '/figures/$id': typeof FiguresIdRoute
  '/history/$id': typeof HistoryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/en/': typeof EnIndexRoute
  '/figures/': typeof FiguresIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/import': typeof AdminArticlesImportRoute
  '/admin/cities/$id': typeof AdminCitiesIdRoute
  '/admin/figures/$id': typeof AdminFiguresIdRoute
  '/admin/history/$id': typeof AdminHistoryIdRoute
  '/en/articles/$id': typeof EnArticlesIdRoute
  '/en/cities/$id': typeof EnCitiesIdRoute
  '/en/figures/$id': typeof EnFiguresIdRoute
  '/en/history/$id': typeof EnHistoryIdRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/cities/': typeof AdminCitiesIndexRoute
  '/admin/figures/': typeof AdminFiguresIndexRoute
  '/admin/history/': typeof AdminHistoryIndexRoute
  '/en/articles/': typeof EnArticlesIndexRoute
  '/en/cities/': typeof EnCitiesIndexRoute
  '/en/figures/': typeof EnFiguresIndexRoute
  '/en/history/': typeof EnHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/en'
    | '/search'
    | '/sitemap.xml'
    | '/admin/settings'
    | '/admin/suggested'
    | '/admin/login'
    | '/articles/$id'
    | '/cities/$id'
    | '/en/about'
    | '/en/search'
    | '/figures/$id'
    | '/history/$id'
    | '/admin/'
    | '/articles/'
    | '/cities/'
    | '/en/'
    | '/figures/'
    | '/history/'
    | '/admin/articles/$id'
    | '/admin/articles/import'
    | '/admin/cities/$id'
    | '/admin/figures/$id'
    | '/admin/history/$id'
    | '/en/articles/$id'
    | '/en/cities/$id'
    | '/en/figures/$id'
    | '/en/history/$id'
    | '/admin/articles/'
    | '/admin/cities/'
    | '/admin/figures/'
    | '/admin/history/'
    | '/en/articles/'
    | '/en/cities/'
    | '/en/figures/'
    | '/en/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/search'
    | '/sitemap.xml'
    | '/admin/settings'
    | '/admin/suggested'
    | '/admin/login'
    | '/articles/$id'
    | '/cities/$id'
    | '/en/about'
    | '/en/search'
    | '/figures/$id'
    | '/history/$id'
    | '/admin'
    | '/articles'
    | '/cities'
    | '/en'
    | '/figures'
    | '/history'
    | '/admin/articles/$id'
    | '/admin/articles/import'
    | '/admin/cities/$id'
    | '/admin/figures/$id'
    | '/admin/history/$id'
    | '/en/articles/$id'
    | '/en/cities/$id'
    | '/en/figures/$id'
    | '/en/history/$id'
    | '/admin/articles'
    | '/admin/cities'
    | '/admin/figures'
    | '/admin/history'
    | '/en/articles'
    | '/en/cities'
    | '/en/figures'
    | '/en/history'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/en'
    | '/search'
    | '/sitemap.xml'
    | '/admin/settings'
    | '/admin/suggested'
    | '/admin_/login'
    | '/articles/$id'
    | '/cities/$id'
    | '/en/about'
    | '/en/search'
    | '/figures/$id'
    | '/history/$id'
    | '/admin/'
    | '/articles/'
    | '/cities/'
    | '/en/'
    | '/figures/'
    | '/history/'
    | '/admin/articles/$id'
    | '/admin/articles/import'
    | '/admin/cities/$id'
    | '/admin/figures/$id'
    | '/admin/history/$id'
    | '/en/articles/$id'
    | '/en/cities/$id'
    | '/en/figures/$id'
    | '/en/history/$id'
    | '/admin/articles/'
    | '/admin/cities/'
    | '/admin/figures/'
    | '/admin/history/'
    | '/en/articles/'
    | '/en/cities/'
    | '/en/figures/'
    | '/en/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  EnRoute: typeof EnRouteWithChildren
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
  CitiesIdRoute: typeof CitiesIdRoute
  FiguresIdRoute: typeof FiguresIdRoute
  HistoryIdRoute: typeof HistoryIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
  FiguresIndexRoute: typeof FiguresIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/': {
      id: '/figures/'
      path: '/figures'
      fullPath: '/figures/'
      preLoaderRoute: typeof FiguresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/cities/': {
      id: '/cities/'
      path: '/cities'
      fullPath: '/cities/'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/$id': {
      id: '/figures/$id'
      path: '/figures/$id'
      fullPath: '/figures/$id'
      preLoaderRoute: typeof FiguresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/search': {
      id: '/en/search'
      path: '/search'
      fullPath: '/en/search'
      preLoaderRoute: typeof EnSearchRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/cities/$id': {
      id: '/cities/$id'
      path: '/cities/$id'
      fullPath: '/cities/$id'
      preLoaderRoute: typeof CitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suggested': {
      id: '/admin/suggested'
      path: '/suggested'
      fullPath: '/admin/suggested'
      preLoaderRoute: typeof AdminSuggestedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/en/history/': {
      id: '/en/history/'
      path: '/history'
      fullPath: '/en/history/'
      preLoaderRoute: typeof EnHistoryIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/figures/': {
      id: '/en/figures/'
      path: '/figures'
      fullPath: '/en/figures/'
      preLoaderRoute: typeof EnFiguresIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/cities/': {
      id: '/en/cities/'
      path: '/cities'
      fullPath: '/en/cities/'
      preLoaderRoute: typeof EnCitiesIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/articles/': {
      id: '/en/articles/'
      path: '/articles'
      fullPath: '/en/articles/'
      preLoaderRoute: typeof EnArticlesIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/admin/history/': {
      id: '/admin/history/'
      path: '/history'
      fullPath: '/admin/history/'
      preLoaderRoute: typeof AdminHistoryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/figures/': {
      id: '/admin/figures/'
      path: '/figures'
      fullPath: '/admin/figures/'
      preLoaderRoute: typeof AdminFiguresIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cities/': {
      id: '/admin/cities/'
      path: '/cities'
      fullPath: '/admin/cities/'
      preLoaderRoute: typeof AdminCitiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/en/history/$id': {
      id: '/en/history/$id'
      path: '/history/$id'
      fullPath: '/en/history/$id'
      preLoaderRoute: typeof EnHistoryIdRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/figures/$id': {
      id: '/en/figures/$id'
      path: '/figures/$id'
      fullPath: '/en/figures/$id'
      preLoaderRoute: typeof EnFiguresIdRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/cities/$id': {
      id: '/en/cities/$id'
      path: '/cities/$id'
      fullPath: '/en/cities/$id'
      preLoaderRoute: typeof EnCitiesIdRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/articles/$id': {
      id: '/en/articles/$id'
      path: '/articles/$id'
      fullPath: '/en/articles/$id'
      preLoaderRoute: typeof EnArticlesIdRouteImport
      parentRoute: typeof EnRoute
    }
    '/admin/history/$id': {
      id: '/admin/history/$id'
      path: '/history/$id'
      fullPath: '/admin/history/$id'
      preLoaderRoute: typeof AdminHistoryIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/figures/$id': {
      id: '/admin/figures/$id'
      path: '/figures/$id'
      fullPath: '/admin/figures/$id'
      preLoaderRoute: typeof AdminFiguresIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cities/$id': {
      id: '/admin/cities/$id'
      path: '/cities/$id'
      fullPath: '/admin/cities/$id'
      preLoaderRoute: typeof AdminCitiesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/import': {
      id: '/admin/articles/import'
      path: '/articles/import'
      fullPath: '/admin/articles/import'
      preLoaderRoute: typeof AdminArticlesImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSuggestedRoute: typeof AdminSuggestedRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesImportRoute: typeof AdminArticlesImportRoute
  AdminCitiesIdRoute: typeof AdminCitiesIdRoute
  AdminFiguresIdRoute: typeof AdminFiguresIdRoute
  AdminHistoryIdRoute: typeof AdminHistoryIdRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminCitiesIndexRoute: typeof AdminCitiesIndexRoute
  AdminFiguresIndexRoute: typeof AdminFiguresIndexRoute
  AdminHistoryIndexRoute: typeof AdminHistoryIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSuggestedRoute: AdminSuggestedRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesImportRoute: AdminArticlesImportRoute,
  AdminCitiesIdRoute: AdminCitiesIdRoute,
  AdminFiguresIdRoute: AdminFiguresIdRoute,
  AdminHistoryIdRoute: AdminHistoryIdRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminCitiesIndexRoute: AdminCitiesIndexRoute,
  AdminFiguresIndexRoute: AdminFiguresIndexRoute,
  AdminHistoryIndexRoute: AdminHistoryIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnSearchRoute: typeof EnSearchRoute
  EnIndexRoute: typeof EnIndexRoute
  EnArticlesIdRoute: typeof EnArticlesIdRoute
  EnCitiesIdRoute: typeof EnCitiesIdRoute
  EnFiguresIdRoute: typeof EnFiguresIdRoute
  EnHistoryIdRoute: typeof EnHistoryIdRoute
  EnArticlesIndexRoute: typeof EnArticlesIndexRoute
  EnCitiesIndexRoute: typeof EnCitiesIndexRoute
  EnFiguresIndexRoute: typeof EnFiguresIndexRoute
  EnHistoryIndexRoute: typeof EnHistoryIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnSearchRoute: EnSearchRoute,
  EnIndexRoute: EnIndexRoute,
  EnArticlesIdRoute: EnArticlesIdRoute,
  EnCitiesIdRoute: EnCitiesIdRoute,
  EnFiguresIdRoute: EnFiguresIdRoute,
  EnHistoryIdRoute: EnHistoryIdRoute,
  EnArticlesIndexRoute: EnArticlesIndexRoute,
  EnCitiesIndexRoute: EnCitiesIndexRoute,
  EnFiguresIndexRoute: EnFiguresIndexRoute,
  EnHistoryIndexRoute: EnHistoryIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  EnRoute: EnRouteWithChildren,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  ArticlesIdRoute: ArticlesIdRoute,
  CitiesIdRoute: CitiesIdRoute,
  FiguresIdRoute: FiguresIdRoute,
  HistoryIdRoute: HistoryIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  CitiesIndexRoute: CitiesIndexRoute,
  FiguresIndexRoute: FiguresIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
